services:
  passvault:
    build:
      context: .             # Using current folder (PASSVAULT)
      dockerfile: Dockerfile # Dockerfile is in current folder
    ports:
      - "5173:5173"   # Frontend (Vite)
      - "5001:5001"   # Backend (Node)
    volumes:
      - .:/app
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123

volumes:
  mongo_data:


